import type { Metadata } from 'next'
import { Suspense } from 'react'
import { Montserrat } from 'next/font/google'

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import CartModal from '@/components/Modals/CartModal'
import LoginModal from '@/components/Modals/LoginModal'
import NavbarModal from '@/components/Modals/NavbarModal'
import SearchModal from '@/components/Modals/SearchModal'
import './globals.css'

const montserrat = Montserrat({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    variable: '--var-montserrat',
    display: 'swap'
})
export const metadata: Metadata = {
    title: 'Ecommerce',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ru">
            <body
                className={`${montserrat.variable} flex flex-col min-h-screen relative `}
            >
                <Header />

                <main className="container flex-1 px-6  my-8 " >{children}</main>

                <Suspense fallback={<div>Loading...</div>}>
                    <NavbarModal />
                    <SearchModal />
                    <CartModal />
                    <LoginModal />
                </Suspense>
                <Footer />
            </body>
        </html>
    )
}
